export const COGNITIVE_GOVERNOR_SCHEMA_VERSION = "1.0";
export const COGNITIVE_EPISODE_SCHEMA_VERSION = "1.0";
export const LESSON_CANDIDATE_SCHEMA_VERSION = "1.0";
export const GOVERNOR_EXECUTION_PROOF_SCHEMA_VERSION = "1.1";

export const MAX_COGNITIVE_ACTIONS = 16;
export const MAX_COGNITIVE_EPISODE_BYTES = 32768;
export const MAX_LESSON_CANDIDATE_BYTES = 8192;

export const COGNITIVE_ACTION = Object.freeze({
  ACQUIRE_INITIAL_EVIDENCE: "ACQUIRE_INITIAL_EVIDENCE",
  REFINE_EVIDENCE_SEARCH: "REFINE_EVIDENCE_SEARCH",
  VERIFY_DIRECT_PAGE: "VERIFY_DIRECT_PAGE",
  REQUEST_CUSTOMER_INPUT: "REQUEST_CUSTOMER_INPUT",
  FINALIZE_EVIDENCE: "FINALIZE_EVIDENCE",
  PROCEED_TO_PURPOSE_JUDGMENT: "PROCEED_TO_PURPOSE_JUDGMENT",
  STOP_INSUFFICIENT_EVIDENCE: "STOP_INSUFFICIENT_EVIDENCE",
  STOP_COMPLETE: "STOP_COMPLETE"
});

export const COGNITIVE_BOUNDARY = Object.freeze({
  AUTO: "AUTO",
  INITIAL_ACQUISITION: "INITIAL_ACQUISITION",
  REFINEMENT: "REFINEMENT",
  DIRECT_PAGE: "DIRECT_PAGE",
  CUSTOMER_INPUT: "CUSTOMER_INPUT",
  FINALIZATION: "FINALIZATION",
  PURPOSE_JUDGMENT: "PURPOSE_JUDGMENT",
  TERMINAL: "TERMINAL"
});

export const COGNITIVE_REASON = Object.freeze({
  INITIAL_PLAN_READY: "INITIAL_PLAN_READY",
  INITIAL_ACQUISITION_ALREADY_EXECUTED: "INITIAL_ACQUISITION_ALREADY_EXECUTED",
  VERIFIED_EXACT_EVIDENCE_SUFFICIENT: "VERIFIED_EXACT_EVIDENCE_SUFFICIENT",
  QUALIFIED_DIRECT_PAGE_CAN_RESOLVE_FACTS: "QUALIFIED_DIRECT_PAGE_CAN_RESOLVE_FACTS",
  MATERIAL_REFINEMENT_AVAILABLE: "MATERIAL_REFINEMENT_AVAILABLE",
  REFINEMENT_ALREADY_EXECUTED: "REFINEMENT_ALREADY_EXECUTED",
  SPECIFIC_CUSTOMER_FACT_MORE_USEFUL: "SPECIFIC_CUSTOMER_FACT_MORE_USEFUL",
  NO_POSITIVE_EVIDENCE_ACTION_REMAINS: "NO_POSITIVE_EVIDENCE_ACTION_REMAINS",
  CANONICAL_EVIDENCE_READY: "CANONICAL_EVIDENCE_READY",
  PURPOSE_JUDGMENT_READY: "PURPOSE_JUDGMENT_READY",
  EVALUATION_COMPLETE: "EVALUATION_COMPLETE",
  PROVIDER_CAPACITY_EXHAUSTED: "PROVIDER_CAPACITY_EXHAUSTED",
  DIRECT_PAGE_CAPACITY_EXHAUSTED: "DIRECT_PAGE_CAPACITY_EXHAUSTED",
  DUPLICATE_ACTION_BLOCKED: "DUPLICATE_ACTION_BLOCKED",
  SEMANTICALLY_DUPLICATE_QUERY_BLOCKED: "SEMANTICALLY_DUPLICATE_QUERY_BLOCKED",
  NO_MATERIAL_STATE_CHANGE: "NO_MATERIAL_STATE_CHANGE",
  CYCLE_DETECTED: "CYCLE_DETECTED",
  INSUFFICIENT_EVIDENCE: "INSUFFICIENT_EVIDENCE"
});
