export const COGNITIVE_GOVERNOR_SCHEMA_VERSION = "1.1";
export const COGNITIVE_EPISODE_SCHEMA_VERSION = "1.0";
export const LESSON_CANDIDATE_SCHEMA_VERSION = "1.0";
export const GOVERNOR_EXECUTION_PROOF_SCHEMA_VERSION = "1.1";

export const MAX_COGNITIVE_ACTIONS = 16;
export const MAX_COGNITIVE_EPISODE_BYTES = 32768;
export const MAX_LESSON_CANDIDATE_BYTES = 8192;

export const COGNITIVE_ACTION = Object.freeze({
  ACQUIRE_INITIAL_EVIDENCE: "ACQUIRE_INITIAL_EVIDENCE",
  REFINE_EVIDENCE_SEARCH: "REFINE_EVIDENCE_SEARCH",
  VERIFY_DIRECT_PAGE: "VERIFY_DIRECT_PAGE",
  EVALUATE_RETURNED_EVIDENCE: "EVALUATE_RETURNED_EVIDENCE",
  REQUEST_NEW_AUTHORITY: "REQUEST_NEW_AUTHORITY",
  REQUEST_CUSTOMER_INPUT: "REQUEST_CUSTOMER_INPUT",
  FINALIZE_EVIDENCE: "FINALIZE_EVIDENCE",
  PROCEED_TO_PURPOSE_JUDGMENT: "PROCEED_TO_PURPOSE_JUDGMENT",
  STOP_INSUFFICIENT_EVIDENCE: "STOP_INSUFFICIENT_EVIDENCE",
  STOP_NO_SAFE_ADVANCING_ACTION: "STOP_NO_SAFE_ADVANCING_ACTION",
  STOP_COMPLETE: "STOP_COMPLETE"
});

export const COGNITIVE_BOUNDARY = Object.freeze({
  AUTO: "AUTO",
  INITIAL_ACQUISITION: "INITIAL_ACQUISITION",
  REFINEMENT: "REFINEMENT",
  DIRECT_PAGE: "DIRECT_PAGE",
  DOSSIER_EVALUATION: "DOSSIER_EVALUATION",
  AUTHORITY: "AUTHORITY",
  CUSTOMER_INPUT: "CUSTOMER_INPUT",
  FINALIZATION: "FINALIZATION",
  PURPOSE_JUDGMENT: "PURPOSE_JUDGMENT",
  TERMINAL: "TERMINAL"
});

export const COGNITIVE_REASON = Object.freeze({
  INITIAL_PLAN_READY: "INITIAL_PLAN_READY",
  INITIAL_ACQUISITION_ALREADY_EXECUTED: "INITIAL_ACQUISITION_ALREADY_EXECUTED",
  VERIFIED_EXACT_EVIDENCE_SUFFICIENT: "VERIFIED_EXACT_EVIDENCE_SUFFICIENT",
  QUALIFIED_DIRECT_PAGE_CAN_RESOLVE_FACTS: "QUALIFIED_DIRECT_PAGE_CAN_RESOLVE_FACTS",
  RETURNED_EVIDENCE_READY_FOR_EVALUATION: "RETURNED_EVIDENCE_READY_FOR_EVALUATION",
  NEW_AUTHORITY_REQUIRED: "NEW_AUTHORITY_REQUIRED",
  NO_SAFE_ADVANCING_ACTION: "NO_SAFE_ADVANCING_ACTION",
  MATERIAL_REFINEMENT_AVAILABLE: "MATERIAL_REFINEMENT_AVAILABLE",
  REFINEMENT_ALREADY_EXECUTED: "REFINEMENT_ALREADY_EXECUTED",
  SPECIFIC_CUSTOMER_FACT_MORE_USEFUL: "SPECIFIC_CUSTOMER_FACT_MORE_USEFUL",
  NO_POSITIVE_EVIDENCE_ACTION_REMAINS: "NO_POSITIVE_EVIDENCE_ACTION_REMAINS",
  CANONICAL_EVIDENCE_READY: "CANONICAL_EVIDENCE_READY",
  PURPOSE_JUDGMENT_READY: "PURPOSE_JUDGMENT_READY",
  EVALUATION_COMPLETE: "EVALUATION_COMPLETE",
  PROVIDER_CAPACITY_EXHAUSTED: "PROVIDER_CAPACITY_EXHAUSTED",
  DIRECT_PAGE_CAPACITY_EXHAUSTED: "DIRECT_PAGE_CAPACITY_EXHAUSTED",
  DUPLICATE_ACTION_BLOCKED: "DUPLICATE_ACTION_BLOCKED",
  SEMANTICALLY_DUPLICATE_QUERY_BLOCKED: "SEMANTICALLY_DUPLICATE_QUERY_BLOCKED",
  NO_MATERIAL_STATE_CHANGE: "NO_MATERIAL_STATE_CHANGE",
  CYCLE_DETECTED: "CYCLE_DETECTED",
  INSUFFICIENT_EVIDENCE: "INSUFFICIENT_EVIDENCE",
  AWAITING_CUSTOMER_INPUT: "AWAITING_CUSTOMER_INPUT",
  INSUFFICIENT_IDENTITY: "INSUFFICIENT_IDENTITY",
  NO_USEFUL_KNOWLEDGE_ACTION_REMAINS: "NO_USEFUL_KNOWLEDGE_ACTION_REMAINS",
  UNRESOLVED_CRITICAL_SAFETY: "UNRESOLVED_CRITICAL_SAFETY",
  CRITICAL_SAFETY_DISPOSITION_REQUIRED: "CRITICAL_SAFETY_DISPOSITION_REQUIRED",
  MANDATORY_SAFETY_DISPOSITION_PRESENT: "MANDATORY_SAFETY_DISPOSITION_PRESENT",
  SUBSTANTIVE_TERMINAL_READINESS: "SUBSTANTIVE_TERMINAL_READINESS",
  CAUTIOUS_LIMITED_PURPOSE_SUPPORTED: "CAUTIOUS_LIMITED_PURPOSE_SUPPORTED",
  SAFETY_ONLY_OUTCOME_COMPLETE: "SAFETY_ONLY_OUTCOME_COMPLETE"
});

export const CUSTOMER_INPUT_STATUS = Object.freeze({
  NOT_REQUIRED: "NOT_REQUIRED",
  REQUIRED_NOT_REQUESTED: "REQUIRED_NOT_REQUESTED",
  PENDING: "PENDING",
  AVAILABLE: "AVAILABLE",
  RESOLVED: "RESOLVED"
});

export const SAFETY_STATE = Object.freeze({
  NO_BLOCKING_SAFETY_CONDITION: "NO_BLOCKING_SAFETY_CONDITION",
  CAUTION_REQUIRED: "CAUTION_REQUIRED",
  REMOVE_FROM_SERVICE_REQUIRED: "REMOVE_FROM_SERVICE_REQUIRED",
  UNRESOLVED_CRITICAL_SAFETY: "UNRESOLVED_CRITICAL_SAFETY"
});
